### ISSUE TITLE
Problem exporting results

### ISSUE THREAD

**Issue by fiuderazes** [GaurangPohankar/Python-Google-Places-Extraction#1]
I've tested the solution under windows 10 and I cannot export the collated places data from the GoogleGuiServer.exe file. - for e.g. 148 found locations
The newly created csv.file from the folder is empty or it contains only a few rows of data. Have any idea how can I solve this problem?
T.y.!

**Comment by GaurangPohankar** [comment]
Hello , It was a work in progress . I have updated the code of exe please do check the updated exe . It is named the international.exe , apparently it was working perfectly fine in India as location but was not writing the csv file .  I have updated the code and exe.

**Comment by fiuderazes** [comment]
Working great now! many thanks for your work!
